apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    version: v{{ default .Chart.Version .Values.image.tag }}
    env: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
    env: {{ .Values.env }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 8001
      name: http

